name: Build and Deploy
on:
  push:
    branches:
      - 'master'
jobs:
  docker_login:
    name: Setup Docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  build_backend:
    name: Build & Push Backend Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and push backend
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          tags: mascit/ag:latest
  deploy_backend:
    name: Deploy backend to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: restart backend deployment
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: rollout restart deployment/age-app
    - name: verify deployment
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: rollout status deployment/age-app
